export default {
    REQUEST_UPCOMING_EVENTS: "REQUEST_UPCOMING_EVENTS",
    RECEIVE_MY_LEAGUES: "RECEIVE_MY_LEAGUES",
    RECEIVE_POPULAR_LEAGUES: "RECEIVE_POPULAR_LEAGUES",
    RECEIVE_UPCOMING_EVENTS: "RECEIVE_UPCOMING_EVENTS",
    REQUEST_EVENT: "REQUEST_EVENT",
    RECEIVE_EVENT: "RECEIVE_EVENT",
    RECEIVE_EVENTS: "RECEIVE_EVENTS",
    REQUEST_LEAGUE: "REQUEST_LEAGUE",
    RECEIVE_LEAGUE: "RECEIVE_LEAGUE",
    RECEIVE_LEAGUES: "RECEIVE_LEAGUES",
}